### ISSUE TITLE
Change readMe

### ISSUE THREAD

**Issue by HerveMeste** [Defiize/Quizzeo#3]
After having done change the relative path, we must modify ReadMe to describe the application and add first steps to install

**Comment by Arnours** [comment]
ReadMe : 

This application is a quiz application.
At the moment, it is a country quiz without score.
The soft take data in a country API with the countriesData.js

--------------------------------------------------------------------
Developer install : 
- Download the project repository with Visual sudio Code
- install NPM & all dependencies in package.json : chai jsdom mocha nodemon sinon sonar-scanner supertest
- And test the application with : npm start (localhost:8080/quiz)

**Comment by Arnours** [comment]
Commited in refractor branch, commit : "FIX : Change readMe #3"
